### ISSUE TITLE
Copy on write support

### ISSUE THREAD

**Issue by dolftax** [mayanklahiri/node-superchild#2]
One of the major issue with Node.js fork is , it doesn't behave like syscall fork. Does this module does copy on write?

**Comment by mayanklahiri** [comment]
Hey @dolftax, no -- it's based on node's spawn(). On posix systems, node may use the fork(2) in some cases and do a COW on the underlying node process, but this module is more like a multi-process message-passing system (e.g. MPI/PVM, or Go channels) rather than a process clone.
